# Google Cloud settings
gcp:
  project_name: 
  project_id: 
  # Service account key file local location.
  service_account_file: 
  # Cloud Storage bucket for storing dataset files.
  bucket_name: 

# PostgreSQL connection settings
postgres:
  host: 127.0.0.1
  port: 5432
  dbname: 
  user: 
  password: 
  sslmode: disable

# Celery settings
celery:
  broker: amqp://guest@localhost:5672/

# Crawler settings
crawler:
  working_dir: /tmp
  # The blob name prefix (i.e., top-level folder) for CKAN datasets.
  ckan_blob_prefix: ckan
  # The blob name prefix (i.e., top-level folder) for Socrata datasets.
  socrata_blob_prefix: socrata

# Index settings
index:
  max_records_per_table: 1000000
  minhash_size: 256
  minhash_seed: 43
  hyperloglog_p: 8
  sample_size: 100
  enable_word_vec_data: false
  minhash_lsh_threshold: 0.5

# API Server local settings
apiserver_local:
  host: 127.0.0.1
  port: 8080

# LSH Server local settings
lshserver_local:
  host: 127.0.0.1
  port: 8081
